// apps/vue3-spa/src/pages/Link.vue
<template>
	<div class="link">
		<h2>User List</h2>
		<ul v-if="users.length" class="user-list">
			<li v-for="user in users" :key="user.id">{{ user.name }} - {{ user.email }}</li>
		</ul>
		<div v-else class="error-tip">
			{{ errorMsg || '加载中...' }}
		</div>
	</div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import axios from 'axios'

const users = ref([])
const errorMsg = ref('')

onMounted(async () => {
	try {
		const res = await axios.get('/api/user/all')
		// 检查接口返回结构
		if (res.data && Array.isArray(res.data.data)) {
			users.value = res.data.data
		} else {
			errorMsg.value = '请求失败'
		}
	} catch (err) {
		console.error('请求失败', err)
		errorMsg.value = '请求失败'
	}
})
</script>

<style scoped>
.user-list {
	margin-top: 20px;
	list-style: none;
}

.user-list li {
	padding: 10px 0;
	border-bottom: 1px solid #ccc;
}

.error-tip {
	margin-top: 20px;
	color: #ff4d4f;
	font-weight: 500;
}
</style>

// apps/next-ssg/app/link/page.tsx
'use client'

import { useEffect, useState } from 'react'

export default function LinkPage() {
	const [userList, setUserList] = useState<any[]>([])
	const [errorMsg, setErrorMsg] = useState('')

	useEffect(() => {
		async function fetchUser() {
			try {
				const response = await fetch('/api/user/all')
				if (!response.ok) throw new Error('接口请求异常')
				const res = await response.json()
				setUserList(res.data)
			} catch (err: any) {
				setErrorMsg(err.message)
			}
		}
		fetchUser()
	}, [])

	return (
		<>
			<h2>User List</h2>
			{errorMsg && <div className="error-tip">{errorMsg}</div>}
			{userList.length === 0 && !errorMsg && <div>加载中...</div>}
			<ul className="user-list">
				{userList.map(item => (
					<li key={item.id}>
						{item.name} - {item.email}
					</li>
				))}
			</ul>
		</>
	)
}
